#!/usr/bin/env bash
# ===========================================================================
# gen-secrets.sh — generate the secrets the k3s quickstart can't generate for
# you, and wire them into the Dex config + the app overlays.
#
# What's generated HERE vs by the charts:
#   - HERE: the TWO Dex OIDC client secrets (one per app). Dex needs the
#     plaintext in its config AND each app needs the SAME plaintext as its
#     OIDC_CLIENT_SECRET — so we mint them and write them to both sides.
#   - HERE (explicit, so they're visible/rotatable): forge-web SESSION_SECRET +
#     AGENTKITFORGE_WEB_SECRET, market SESSION_SECRET, market ADMIN_API_KEY.
#     (If you delete these from the output files, the charts generate + persist
#     their own instead — but we set them so clone→login is deterministic.)
#
# Outputs (all GIT-IGNORED; the committed dex/dex-values.yaml is left untouched):
#   dex/dex-values.generated.yaml   : Dex config with client secrets injected
#   secrets.forge.generated.yaml    : forge-web `-f` overlay
#   secrets.market.generated.yaml   : market   `-f` overlay
#
# Usage:
#   ./gen-secrets.sh
# Re-running mints fresh secrets; `helm upgrade` both releases afterwards.
# ===========================================================================
set -euo pipefail
cd "$(dirname "$0")"

hex() { openssl rand -hex 32; }       # 64 hex chars
b64() { openssl rand -base64 32; }    # >= 32 bytes (SESSION_SECRET minimum)

FORGE_OIDC_CLIENT_SECRET="$(hex)"
MARKET_OIDC_CLIENT_SECRET="$(hex)"
AUTO_OIDC_CLIENT_SECRET="$(hex)"
FORGE_SESSION_SECRET="$(b64)"
FORGE_WEB_SECRET="$(b64)"             # AGENTKITFORGE_WEB_SECRET (AES-256-GCM key)
MARKET_SESSION_SECRET="$(b64)"
MARKET_ADMIN_API_KEY="$(hex)"
AUTO_SESSION_SECRET="$(b64)"
AUTO_WEB_SECRET="$(b64)"              # AGENTKITFORGE_WEB_SECRET (AES-256-GCM key)

# --- 1. Inject the client secrets into a COPY of the Dex config ------------
# (Leaves the committed dex/dex-values.yaml template with its placeholders.)
sed \
  -e "s|<FORGE_OIDC_CLIENT_SECRET>|${FORGE_OIDC_CLIENT_SECRET}|g" \
  -e "s|<MARKET_OIDC_CLIENT_SECRET>|${MARKET_OIDC_CLIENT_SECRET}|g" \
  -e "s|<AUTO_OIDC_CLIENT_SECRET>|${AUTO_OIDC_CLIENT_SECRET}|g" \
  dex/dex-values.yaml > dex/dex-values.generated.yaml

# --- 2. forge-web secrets overlay (field paths match charts/agentkitforge-web) ---
cat > secrets.forge.generated.yaml <<EOF
# GENERATED by gen-secrets.sh — DO NOT COMMIT. Pass to the forge-web install:
#   helm ... -f secrets.forge.generated.yaml
web:
  secrets:
    oidcClientSecret: "${FORGE_OIDC_CLIENT_SECRET}"   # -> OIDC_CLIENT_SECRET
    sessionSecret: "${FORGE_SESSION_SECRET}"          # -> SESSION_SECRET
    forgeWebSecret: "${FORGE_WEB_SECRET}"             # -> AGENTKITFORGE_WEB_SECRET
EOF

# --- 3. market secrets overlay (field paths match agentkitmarket chart) ----
cat > secrets.market.generated.yaml <<EOF
# GENERATED by gen-secrets.sh — DO NOT COMMIT. Pass to the market install:
#   helm ... -f secrets.market.generated.yaml
web:
  secrets:
    oidcClientSecret: "${MARKET_OIDC_CLIENT_SECRET}"  # -> OIDC_CLIENT_SECRET
    sessionSecret: "${MARKET_SESSION_SECRET}"         # -> SESSION_SECRET
secrets:
  adminApiKey: "${MARKET_ADMIN_API_KEY}"              # -> ADMIN_API_KEY (web reuses it)
EOF

# --- 4. auto secrets overlay (field paths match charts/agentkitauto) -------
# NOTE: ANTHROPIC_API_KEY is BYO and NOT minted here — supply it at install with
# --set auto.anthropicApiKey=sk-ant-... (or add it under auto: below). The Auto
# worker service key is chart-generated.
cat > secrets.auto.generated.yaml <<EOF
# GENERATED by gen-secrets.sh — DO NOT COMMIT. Pass to the agentkitauto install:
#   helm ... -f secrets.auto.generated.yaml --set auto.anthropicApiKey=sk-ant-...
web:
  secrets:
    oidcClientSecret: "${AUTO_OIDC_CLIENT_SECRET}"    # -> OIDC_CLIENT_SECRET
    sessionSecret: "${AUTO_SESSION_SECRET}"           # -> SESSION_SECRET
    forgeWebSecret: "${AUTO_WEB_SECRET}"              # -> AGENTKITFORGE_WEB_SECRET
EOF

echo "Wrote: dex/dex-values.generated.yaml (client secrets injected)"
echo "Wrote: secrets.forge.generated.yaml"
echo "Wrote: secrets.market.generated.yaml"
echo "Wrote: secrets.auto.generated.yaml"
echo
echo "  Forge  OIDC client secret : ${FORGE_OIDC_CLIENT_SECRET}"
echo "  Market OIDC client secret : ${MARKET_OIDC_CLIENT_SECRET}"
echo "  Auto   OIDC client secret : ${AUTO_OIDC_CLIENT_SECRET}"
echo "  Market ADMIN_API_KEY      : ${MARKET_ADMIN_API_KEY}"
echo
echo "Next: set NODE_IP + run the sed step (README.md), then helm install."
echo "      (AgentKitAuto also needs a BYO ANTHROPIC_API_KEY at install time.)"
